### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by jenstornell** [samnabi/kirby-panoramio#1]
If it still works, you can add it here if you want.

https://github.com/jenstornell/kirby-plugins/issues

**Comment by jenstornell** [comment]
I added it...
https://github.com/jenstornell/kirby-plugins/issues/108

**Comment by samnabi** [comment]
Yeah, it's just a simple PHP function, although it was made for Kirby 1, I see no reason why it shouldn't work with K2
